backend/controllers/UserController.php
<?php

namespace backend\controllers;

use common\models\Statistics;
use Yii;
use yii\data\ActiveDataProvider;
use yii\web\NotFoundHttpException;

use common\models\User;
use common\models\UserSearch;
use common\models\UserInvite;
use common\models\UserInviteSearch;

class UserController extends \yii\web\Controller
{
    public function actionToggle($id)
    {
        $model = User::findOne($id);
        if (!$model) throw new NotFoundHttpException;
    
        $model->enabled = !$model->enabled;
        $model->save(false, ['enabled']);

        return $this->redirect(Yii::$app->request->referrer);
    }

    public function actionDelete()
    {
        $ids = Yii::$app->request->post('ids');
        $models = User::find()->andWhere(['id' => $ids])->all();

        foreach($models as $model)
        {
            $model->delete();
        }

        Yii::$app->session->addFlash('success', 'Выбранные пользователи удалены');

        return $this->redirect(Yii::$app->request->referrer);
    }

    public function actionUpdate($id)
    {
        if ($id)
        {
            $model = User::findOne($id);
            if (!$model) throw NotFoundHttpException;
        }
        else
        {
            $model = new User;
        }

        $passwordModel = new \common\forms\UserChangePassword([
            'isNewRecord' => $model->isNewRecord,
        ]);

        if ($model->load(Yii::$app->request->post()) && $passwordModel->load(Yii::$app->request->post()))
        {
            $model->photo_file = \yii\web\UploadedFile::getInstance($model, 'photo_file');
            if ($model->validate() && $passwordModel->validate())
            {   
                if ($model->photo_file)
                {
                    $path = Yii::getAlias('@frontend').'/web/uploads/users/';
                    $name = Yii::$app->security->generateRandomString(16).".".$model->photo_file->extension;
                    $model->photo = $name;
                    $model->photo_file->saveAs($path.$name, false);
                }
                
                if (!empty($passwordModel->password)) $model->password = $passwordModel->password;

                // Отключаем валидацию, т.к. она уже прошла и она ломает дату
                // @todo Переделать на DateBehavior
                $model->save(false);
                Yii::$app->session->addFlash('success', 'Данные пользователя успешно сохранены');
                return $this->goBack();
            }
        }
        else
        {
            Yii::$app->user->returnUrl = Yii::$app->request->referrer;
        }

        return $this->render('update', [
            'model' => $model,
            'passwordModel' => $passwordModel,
        ]);
    }

    public function actionView($id)
    {
        $model = User::findOne($id);
        if (!$model) throw NotFoundHttpException;

        $visits_count = Statistics::find()
            ->where(['type_id'=>Statistics::TYPE_USER_VISIT])
            ->andWhere('created_at > DATE_SUB(now(), INTERVAL 30 DAY)')
            ->count();

        $service_display = Statistics::find()
            ->innerJoin(['service s', 'service_id = s.id'])
            ->innerJoin('company c', 'c.user_id = ' . $model->id)
            ->where(['statistics.type_id'=>Statistics::TYPE_SERVICE_DISPLAY])
            ->andWhere('s.company_id = c.id')
            ->andWhere('statistics.created_at > DATE_SUB(now(), INTERVAL 30 DAY)')
            ->count();

        $redirects_service =  Statistics::find()
            ->innerJoin(['service s', 'service_id = s.id'])
            ->innerJoin('company c', 'c.user_id = ' . $model->id)
            ->where(['statistics.type_id'=>Statistics::TYPE_SERVICE_VIEW])
            ->andWhere('s.company_id = c.id')
            ->andWhere('statistics.created_at > DATE_SUB(now(), INTERVAL 30 DAY)')
            ->count();

        $favorites = Statistics::find()
            ->innerJoin(['service s', 'service_id = s.id'])
            ->innerJoin('company c', 'c.user_id = ' . $model->id)
            ->where(['statistics.type_id'=>Statistics::TYPE_FAVORITE_ADDED])
            ->andWhere('s.company_id = c.id')
            ->andWhere('statistics.created_at > DATE_SUB(now(), INTERVAL 30 DAY)')
            ->count();

        return $this->render('view', [
            'model' => $model,
            'visits_count'=>$visits_count,
            'service_display'=>$service_display,
            'redirects_service'=>$redirects_service,
            'favorites'=>$favorites
        ]);
    }

    public function actionInviteDelete()
    {
        $models = UserInvite::find()->andWhere(['id' => Yii::$app->request->post('ids')])->all();

        foreach($models as $model)
        {
            $model->delete();
        }

        Yii::$app->session->addFlash('success', 'Выбранные приглашения успешно удалены');
        return $this->redirect(Yii::$app->request->referrer);
    }

    public function actionInviteUpdate($id)
    {
        if ($id)
        {
            $model = UserInvite::findOne($id);
            if (!$model) throw NotFoundHttpException;
        }
        else
        {
            $model = new UserInvite;
        }

        if ($model->load(Yii::$app->request->post()) && $model->save())
        {
            $url = Yii::$app->frontendUrlManager->createAbsoluteUrl(['/user/register', 'code' => $model->code]);
            Yii::$app->session->addFlash('success', 'Приглашение успешно сохранено. Ссылка на регистрацию пользователя <a href="#">'.$url.'</a>');

            return $this->goBack();
        }
        else
        {
            Yii::$app->user->returnUrl = Yii::$app->request->referrer;
        }

        return $this->render('invite-update', [
            'model' => $model,
        ]);
    }

    public function actionInvite()
    {
        $searchModel = new UserInviteSearch;
        $dataProvider = $searchModel->search(Yii::$app->request->get());

        return $this->render('invite', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    public function actionIndex()
    {
        $searchModel = new UserSearch;
        $dataProvider = $searchModel->search(Yii::$app->request->get());

        return $this->render('index', [
            'dataProvider' => $dataProvider,
            'searchModel' => $searchModel,
        ]);
    }

    public function actionRegister($code = false)
    {
        $invite = UserInvite::find()->andWhere(['code' => $code, 'user_id' => null])->one();
        //if (!$invite) throw new NotFoundHttpException;

        $model = new \frontend\forms\UserRegister;

        if ($model->load(Yii::$app->request->post()) && $model->validate())
        {
            $user = new User([
                'email' => $model->email,
                'contract_number' => $invite ? $invite->contract_number : null,
                'role' => 'partner', 
            ]);
            $user->setPassword($model->password);
            $user->save();
            
            $invite->user_id = $user->id;
            $invite->save(false, ['user_id']);

            Yii::$app->user->login($user, 60*60*24*365);
            return $this->redirect(['/company/form']);
        }

        $this->layout = 'login';
        return $this->render('register', [
            'model' => $model,
        ]);
    }

    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) return $this->redirect(['/site/index']);

        $model = new \backend\forms\UserLogin;

        if ($model->load(Yii::$app->request->post()) && $model->validate())
        {
            Yii::$app->user->login($model->getUser(), $model->rememberMe ? 60*60*24*365 : 0);
            return $this->redirect(['/site/index']);
        }

        $this->layout = 'login';
        return $this->render('login', [
            'model' => $model,
        ]);
    }

    public function actionLogout()
    {
        Yii::$app->user->logout();
        return $this->redirect(Yii::$app->frontendUrlManager->createUrl(['/site/index']));
    }
}

frontend/controllers/UserController.php
<?php

namespace frontend\controllers;

use common\models\Company;
use Yii;
use yii\web\NotFoundHttpException;

use common\models\Page;
use common\models\User;
use common\models\UserSocial;

class UserController extends \yii\web\Controller
{
    public function actions()
    {
        return [
            'auth' => [
                'class' => 'yii\authclient\AuthAction',
                'successCallback' => [$this, 'onAuthSuccess'],
            ],
        ];
    }

    public function onAuthSuccess($client)
    {
        $attributes = $client->getUserAttributes();

        if ($client->id == 'odnoklassniki') $attributes['id'] = $attributes['uid'];

        $auth = UserSocial::find()->where([
            'source' => $client->id,
            'source_id' => $attributes['id'],
        ])->one();

        if (!$auth)
        {
            $user = new User;

            switch($client->id)
            {
                case 'google':
                    $user->first_name = $attributes['name']['givenName'];
                    break;
                case 'vkontakte':
                case 'odnoklassniki':
                    $user->first_name = $attributes['first_name'];
                    $user->last_name = $attributes['last_name'];
                    break;
                case 'facebook':
                    list($user->first_name, $user->last_name) = explode(" ",$attributes['name']);
                    break;
            }

            $user->save();
            $auth = new UserSocial([
                'user_id' => $user->id,
                'source' => $client->id,
                'source_id' => $attributes['id'],
            ]);
            $auth->save();

        }
        if ($auth->user->enabled)
        {
            Yii::$app->user->login($auth->user, 60*60*24*365);
        }
//        return $this->redirect(['/site/index']);
    }

    public function actionEmailConfirm($token = false)
    {
        if (!$token)
        {
            return $this->render('email-confirm', [
            ]);
        }

        $user = User::findOne(['activation_token' => $token]);
        if (!$user) return $this->redirect(['/site/index']);

        // У юзера есть мэйл - значит обычная регистрация по мэйлу и паролю
        if (!empty($user->email))
        {
            $user->activation_token = null;
            $user->save(false, ['activation_token']);
        }   
        // Мэйла нет, значит регистрация через соц. сети
        else
        {
            $social = $user->socials[0];
            $oldUser = User::findOne(['email' => $social->email]);
            // Смотрим, есть ли уже юзер с таким мэйлом, если есть то привязываем соц. сеть к нему
            if ($oldUser)
            {
                $social->user_id = $oldUser->id;        
                $social->save(false, ['user_id']);
                $user->delete();
                $user = $oldUser;
            }
            else
            {
                $user->email = $social->email;
                $user->save(false, ['email']);
            }
        }

        Yii::$app->user->logout();
        Yii::$app->user->login($user, 60*60*24*365);
        return $this->redirect(['/site/index']);
    }

    public function actionEmail()
    {
        if (Yii::$app->user->isGuest) return $this->redirect(['/site/index']);

        $model = new \frontend\forms\UserEmail;

        if ($model->load(Yii::$app->request->post()) && $model->validate())
        {
            $user = Yii::$app->user->identity;
            $user->activation_token = Yii::$app->security->generateRandomString(32);
            $user->save();
            $social = $user->socials[0];
            $social->email = $model->email;
            $social->save();

            Yii::$app->mailer->compose('user_email-confirm', ['model' => Yii::$app->user->identity])
                     ->setTo($model->email)
                     ->setSubject('Подтверждение адреса почты')
                     ->send();

            return $this->redirect(['/user/email-confirm']);
        }

        return $this->render('email', [
            'model' => $model,
        ]);
    }

    public function actionReseted()
    {
        return $this->render('reseted', [
        ]);
    }

    public function actionReset($token)
    {
        $user = User::find()->andWhere(['password_reset_token' => $token])->one();
        if (!$user) throw new NotFoundHttpException;

        $model = new \frontend\forms\UserReset;

        if ($model->load(Yii::$app->request->post()) && $model->validate())
        {
            $user->setPassword($model->password);
            $user->password_reset_token = null;
            $user->save();
            Yii::$app->user->login($user);
            return $this->redirect(['/user/reseted']);
        }

        return $this->render('reset', [
            'model' => $model,
        ]);
    }

    public function actionRestored()
    {
        return $this->render('restored');
    }

    public function actionRestore()
    {
        $model = new \frontend\forms\UserRestore;

        if ($model->load(Yii::$app->request->post()) && $model->validate())
        {
            $model->user->password_reset_token = Yii::$app->security->generateRandomString(32);
            $model->user->save(false, ['password_reset_token']);

            Yii::$app->mailer->compose('user_restore', ['model' => $model->user])
                     ->setTo($model->email)
                     ->setSubject('Восстановление пароля')
                     ->send();

            return $this->redirect(['/user/restored']);

        }

        $page = Page::findOne(8);

        return $this->render('restore', [
            'page' => $page,
            'model' => $model,
        ]);
    }

    public function actionRegistered()
    {
        return $this->render('registered', [
        ]);
    }

    public function actionRegister($code = false)
    {
        if ($code) return $this->redirect(Yii::$app->backendUrlManager->createUrl(['/user/register', 'code' => $code]));

        $model = new \frontend\forms\UserRegister;

        if ($model->load(Yii::$app->request->post()))
        {
            if ($model->validate())
            {
                $user = new User([
                    'email' => $model->email,                    
                    'password' => $model->password,
                    'activation_token' => Yii::$app->security->generateRandomString(),
                ]);
                $user->save();
                
                Yii::$app->mailer->compose('user_email-confirm', ['model' => $user])
                     ->setTo($model->email)
                     ->setSubject('Подтверждение адреса почты')
                     ->send();

                return $this->redirect(['/user/email-confirm']);
            }
        }

        return $this->renderAjax('register', [
            'model' => $model,
        ]);
    }

    public function actionLogout()
    {
        Yii::$app->user->logout();
        return $this->redirect(Yii::$app->request->referrer);
    }

    public function actionLogin()
    {
        $model = new \frontend\forms\UserLogin;

        if ($model->load(Yii::$app->request->post()))
        {
            if ($model->validate())
            {
                $user = $model->getUser();
                Yii::$app->user->login($user, 60*60*24*365);
                // Этот хак нужен чтобы pjax перезагрузил страницу. Он перезагружает ее при пустом ответе сервера. При 302 не работает

                if (Yii::$app->user->can('partner')){
                    $haveServices = Company::find()->where(['user_id'=>Yii::$app->user->id])->count();

                    if ($haveServices == 0)
                        return $this->redirect(['/cabinet/company/form']);
                }

                if ($user->location_id){
                    Yii::$app->session->set('location_id', $user->location_id);
                    if ((time() - strtotime($user->updated_at)) > (3 * 24 * 60 * 60)){
                        Yii::$app->session->setFlash('its_time_to_confirm_location', true);
                    }
                }
                else{
                    Yii::$app->session->setFlash('show_location_modal', true);
                }
                return $this->redirect(\yii::$app->request->referrer, 200);
            }
        }

        return $this->renderAjax('login', [
            'model' => $model,
        ]);
    }
}

frontend/views/user/email-confirm.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

$this->title = 'Регистрация';
$this->params['breadcrumbs'] = [
    $this->title
];

?>
<div class="main-block">
    <h2><?=$this->title?></h2>
    <p>На указанный вами адрес была выслана ссылка для продолжения регистрации. Пожалуйста, пройдите по ссылке в письме</p>
</div>

frontend/views/user/email.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

$this->title = 'Регистрация';
$this->params['breadcrumbs'] = [
    $this->title
];

?>
<div class="main-block">
    <h2><?=$this->title?></h2>
    <p>Для продолжения работы с сайтом, необходимо указать E-mail адрес</p>
<?php
    $form = ActiveForm::begin([
        'enableClientValidation' => false,
    ]);

    echo $form->field($model, 'email')
              ->textInput([
                  'placehodler' => 'E-mail',
              ])
              ->label(false);
?>
<div class="text-center">
<?php
    echo Html::submitButton('Далее', ['class' => 'button']);

    $form->end();
?>
</div>
</div>

frontend/views/user/login.php
<?php

use yii\authclient\widgets\AuthChoice;
use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\widgets\Pjax;

Pjax::begin([
    'enablePushState' => false,
    'id' => 'user-login-pjax',
]);

$this->registerJs('

    $(".password-btn").click(function(){
        $(this).find(".fa").toggleClass("fa-eye fa-eye-slash");
        $(this).parent().find("input").attr("type", function(idx, attr){
            return attr == "text" ? "password" : "text";
        });
    });


');
?>
<div class="menu-login-container">
<?php
    $form = ActiveForm::begin([
        'id' => 'user-login-form',
        'action' => ['/user/login'],
        'enableClientValidation' => false,
        'options' => [
            'data-pjax' => true,
        ],
    ]);

    echo $form->field($model, 'email')->textInput([
        'class' => 'login-input',
        'placeholder' => 'Ваш E-mail',
    ])->label(false);
?>
    <div class="password-box">
    <?php
        echo $form->field($model, 'password')->passwordInput([
            'class' => 'password-input',
            'placeholder' => "Ваш пароль",
        ])->label(false);
    ?>
        <button type="button" onclick="" class="password-btn">
            <i class="fa fa-eye"></i>
        </button>
    </div>
    <div class="addit-box">
        <div class="addit-left">
            <input class="addit-checkbox" type="checkbox" id="checkbox-remember-me" />
            <label class="addit-checkbox-label" for="checkbox-remember-me">Запомнить меня</label><br />
            <div class="addit-question">
                <i class="fa">?</i> <?=Html::a('Забыли пароль?', ['/user/restore'], ['data-pjax' => 0])?>
            </div>
        </div>




        <div class="addit-right">
            <button type="submit">Войти</button>

        </div>
    </div>
    <div class="help-block"><?php Yii::$app->request->isAjax?(!Yii::$app->request->validateCsrfToken()?'Данные устарели. Обновите страницу.':''):'' ?></div>
    <div class="auth-separator"></div>
    <div class="social-box">
        <span>Вход через социальные сети</span>
        <?php 
            $authChoice = AuthChoice::begin([
                'baseAuthUrl' => ['/user/auth'],
                'popupMode' => true,
            ]);
        ?>
        <div class="social-icons">
            <?php
                foreach($authChoice->clients as $client)
                {
                    switch($client->id)
                    {
                        case 'google':
                            $class = 'social-gp';
                            break;
                        case 'vkontakte':
                            $class = 'social-vk';
                            break;
                        case 'odnoklassniki':
                            $class = 'social-ok';
                            break;
                        case 'facebook':
                            $class = 'social-fb';
                            break;
                    }
                    echo Html::a('', $authChoice->createClientUrl($client), ['class' => $class]);
                }
            ?>
        </div>
        <?php
            $authChoice->end();
        ?>
    </div>
<?php
    $form->end();
?>
</div>
<?php
    Pjax::end();

frontend/views/user/register.php
<?php

use yii\helpers\Url;
use yii\widgets\ActiveForm;
use yii\widgets\Pjax;

\frontend\assets\AppAsset::register($this);

Pjax::begin([
    'enablePushState' => false,
    'id' => 'user-register-pjax',
]);

?>
<div class="menu-register-container">
<?php
    $form = ActiveForm::begin([
        'id' => 'user-register-form',
        'action' => ['/user/register'],
        'enableClientValidation' => false,
        'options' => [
            'data-pjax' => true,
        ],
    ]);

echo $form->field($model, 'email',[
        'errorOptions' => [
            'encode' => false,
            'class' => 'help-block',
        ],
    ])->textInput([
        'class' => 'login-input',
        'placeholder' => 'Ваш E-mail',
    ])->label(false);
?>
    <div class="password-box">
    <?php
        echo $form->field($model, 'password')->textInput([
            'class' => 'password-input',
            'placeholder' => 'Ваш пароль',
        ])->label(false);
    ?>
        <button type="button" class="password-btn">
            <i class="fa fa-eye-slash"></i>
        </button>
    </div>
        <?=$form->field($model, 'terms', [
        'template' => '{label}{input}<label class="reg-checkbox-label" for="userregister-terms">Я принимаю условия <a href="'.Url::to(['/page/view', 'id' => 6]).'" target="_blank" data-pjax=0>пользовательского соглашения</a></label>{hint}{error}',
        ])->checkbox([
                    'label' => '', //'Я принимаю условия пользовательского соглашения',
                    //'id' => 'checkbox-accept-text',
                    //'class' => 'reg-checkbox',
            ], false);?>
    <button class="reg-btn" type="submit" class="reg-btn">Регистрация</button>
<?php
    $form->end();
?>
</div>
<?php

Pjax::end();

frontend/views/user/registered.php
<?php

$this->title = 'Подтверждение регистрации';
$this->params['breadcrumbs'] = [
    $this->title
];

?>
<div class="main-block">
    <h2><?=$this->title?></h2>
    <p>Вы успешно зарегистрированы. На вашу почту отправлена ссылка для активации аккаунта. Пройдите по ссылке в письме чтобы продолжить работу с сайтом.</p>
</div>

frontend/views/user/reset.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

$this->title = 'Смена пароля';
$this->params['breadcrumbs'] = [
    $this->title
];

?>
<div class="main-block">
    <h2><?=$this->title?></h2>
<?php
    $form = ActiveForm::begin([
        'enableClientValidation' => false,
    ]);

    echo $form->field($model, 'password')->passwordInput(['placeholder' => 'Новый пароль'])->label(false);

    echo $form->field($model, 'password_confirmation')->passwordInput(['placeholder' => 'Подтверждение пароля'])->label(false);


    echo Html::submitButton('Изменить пароль', ['class' => 'btn btn-primary']);

    $form->end();
?>
</div>

frontend/views/user/reseted.php
<?php

$this->title = 'Смена пароля';
$this->params['breadcrumbs'] = [
    $this->title
];

?>
<div class="main-block">
    <h2><?=$this->title?></h2>
    <p>Пароль успешно изменен!</p>
</div>

frontend/views/user/restore.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

$this->title = 'Восстановление пароля';
$this->params['breadcrumbs'] = [
    $this->title
];

?>
<div class="main-block">
    <h2><?=$this->title?></h2>
    <?=$page->text?>
<?php
    $form = ActiveForm::begin([
        'enableClientValidation' => false,
    ]);

    echo $form->field($model, 'email')->textInput(['placeholder' => 'Ваш E-mail'])->label(false);

?>
    <div class="text-center">    
        <?=Html::submitButton('Восстановить', ['class' => 'button'])?>
    </div>
<?php
    $form->end();
?>
</div>

frontend/views/user/restored.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

$this->title = 'Восстановление пароля';
$this->params['breadcrumbs'] = [
    $this->title
];

?>
<div class="main-block">
    <h2><?=$this->title?></h2>
    <p>Ссылка для восстановления пароля отправлена на указанный почтовый адрес</p>
</div>